### ISSUE TITLE
Don't run odrive

### ISSUE THREAD

**Issue by nghiank97** [AustinOwens/robodog#11]
I can't run command - python 3.6,win10

![image](https://user-images.githubusercontent.com/42688892/143853523-9337b140-290b-47c6-94ed-fea79bc30212.png)

**Comment by AustinOwens** [comment]
It looks like `typing.NoReturn` was updated in version 3.6.5 of Python: https://docs.python.org/3.6/library/typing.html#typing.NoReturn

You may want to upgrade to a later version of Python.

**Comment by AustinOwens** [comment]
I assumed this solved the issue so I am closing this issue.
